# Generated by Django 3.0 on 2022-08-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220822_1621'),
        ('myapp', '0003_products_image'),
    ]

    operations = [
    ]
